server:
  port: 35815
spring:
  main:
    lazy-initialization: true
springdoc:
  api-docs:
    path: /v3/api-docs
rarible:
  core:
    ethereum:
      url: localhost
      web-socke-turl: ws://localhost
  protocol:
    erc20:
      api:
        blockchain: ethereum