spring:
  data:
    mongodb:
      uri: mongodb://${mongodb.hosts}
      database: ${mongodb.database}

parityUrls: ${node.hosts}
parityWebSocketUrls: ${node.webSocketHosts}

common:
  kafka-replica-set: ${kafka.hosts}
